spring:
  application:
    name: passkeys
  mail:
    port: 1025
    host: localhost


  sql:
    init:
      mode: always
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
