spring:
  application:
    name: passkeys
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

server:
  servlet:
    session:
      persistent: false